import { Instrument } from "@Interfaces/Instrument";
import { InstrumentUrl } from "@Interfaces/InstrumentUrl";

const InstrumentNames = [
    "acoustic_grand_piano",
    "bright_acoustic_piano",
    "electric_grand_piano",
    "honkytonk_piano",
    "electric_piano_1",
    "electric_piano_2",
    "harpsichord",
    "clavinet",
    "celesta",
    "glockenspiel",
    "music_box",
    "vibraphone",
    "marimba",
    "xylophone",
    "tubular_bells",
    "dulcimer",
    "drawbar_organ",
    "percussive_organ",
    "rock_organ",
    "church_organ",
    "reed_organ",
    "accordion",
    "harmonica",
    "tango_accordion",
    "acoustic_guitar_nylon",
    "acoustic_guitar_steel",
    "electric_guitar_jazz",
    "electric_guitar_clean",
    "electric_guitar_muted",
    "overdriven_guitar",
    "distortion_guitar",
    "guitar_harmonics",
    "acoustic_bass",
    "electric_bass_finger",
    "electric_bass_pick",
    "fretless_bass",
    "slap_bass_1",
    "slap_bass_2",
    "synth_bass_1",
    "synth_bass_2",
    "violin",
    "viola",
    "cello",
    "contrabass",
    "tremolo_strings",
    "pizzicato_strings",
    "orchestral_harp",
    "timpani",
    "string_ensemble_1",
    "string_ensemble_2",
    "synth_strings_1",
    "synth_strings_2",
    "choir_aahs",
    "voice_oohs",
    "synth_choir",
    "orchestra_hit",
    "trumpet",
    "trombone",
    "tuba",
    "muted_trumpet",
    "french_horn",
    "brass_section",
    "synth_brass_1",
    "synth_brass_2",
    "soprano_sax",
    "alto_sax",
    "tenor_sax",
    "baritone_sax",
    "oboe",
    "english_horn",
    "bassoon",
    "clarinet",
    "piccolo",
    "flute",
    "recorder",
    "pan_flute",
    "blown_bottle",
    "shakuhachi",
    "whistle",
    "ocarina",
    "lead_1_square",
    "lead_2_sawtooth",
    "lead_3_calliope",
    "lead_4_chiff",
    "lead_5_charang",
    "lead_6_voice",
    "lead_7_fifths",
    "lead_8_bass__lead",
    "pad_1_new_age",
    "pad_2_warm",
    "pad_3_polysynth",
    "pad_4_choir",
    "pad_5_bowed",
    "pad_6_metallic",
    "pad_7_halo",
    "pad_8_sweep",
    "fx_1_rain",
    "fx_2_soundtrack",
    "fx_3_crystal",
    "fx_4_atmosphere",
    "fx_5_brightness",
    "fx_6_goblins",
    "fx_7_echoes",
    "fx_8_scifi",
    "sitar",
    "banjo",
    "shamisen",
    "koto",
    "kalimba",
    "bagpipe",
    "fiddle",
    "shanai",
    "tinkle_bell",
    "agogo",
    "steel_drums",
    "woodblock",
    "taiko_drum",
    "melodic_tom",
    "synth_drum",
    "reverse_cymbal",
    "guitar_fret_noise",
    "breath_noise",
    "seashore",
    "bird_tweet",
    "telephone_ring",
    "helicopter",
    "applause",
    "gunshot",
];

const GetInstrumentUrls = (name: string): InstrumentUrl => {
    const baseUrl =
        "//gleitz.github.io/midi-js-soundfonts/FluidR3_GM/" + name + "-mp3/";
    return {
        A0: baseUrl + "A0.mp3",
        Bb0: baseUrl + "Bb0.mp3",
        B0: baseUrl + "B0.mp3",

        C1: baseUrl + "C1.mp3",
        Db1: baseUrl + "Db1.mp3",
        D1: baseUrl + "D1.mp3",
        Eb1: baseUrl + "Eb1.mp3",
        E1: baseUrl + "E1.mp3",
        F1: baseUrl + "F1.mp3",
        Gb1: baseUrl + "Gb1.mp3",
        G1: baseUrl + "G1.mp3",
        Ab1: baseUrl + "Ab1.mp3",
        A1: baseUrl + "A1.mp3",
        Bb1: baseUrl + "Bb1.mp3",
        B1: baseUrl + "B1.mp3",

        C2: baseUrl + "C2.mp3",
        Db2: baseUrl + "Db2.mp3",
        D2: baseUrl + "D2.mp3",
        Eb2: baseUrl + "Eb2.mp3",
        E2: baseUrl + "E2.mp3",
        F2: baseUrl + "F2.mp3",
        Gb2: baseUrl + "Gb2.mp3",
        G2: baseUrl + "G2.mp3",
        Ab2: baseUrl + "Ab2.mp3",
        A2: baseUrl + "A2.mp3",
        Bb2: baseUrl + "Bb2.mp3",
        B2: baseUrl + "B2.mp3",

        C3: baseUrl + "C3.mp3",
        Db3: baseUrl + "Db3.mp3",
        D3: baseUrl + "D3.mp3",
        Eb3: baseUrl + "Eb3.mp3",
        E3: baseUrl + "E3.mp3",
        F3: baseUrl + "F3.mp3",
        Gb3: baseUrl + "Gb3.mp3",
        G3: baseUrl + "G3.mp3",
        Ab3: baseUrl + "Ab3.mp3",
        A3: baseUrl + "A3.mp3",
        Bb3: baseUrl + "Bb3.mp3",
        B3: baseUrl + "B3.mp3",

        C4: baseUrl + "C4.mp3",
        Db4: baseUrl + "Db4.mp3",
        D4: baseUrl + "D4.mp3",
        Eb4: baseUrl + "Eb4.mp3",
        E4: baseUrl + "E4.mp3",
        F4: baseUrl + "F4.mp3",
        Gb4: baseUrl + "Gb4.mp3",
        G4: baseUrl + "G4.mp3",
        Ab4: baseUrl + "Ab4.mp3",
        A4: baseUrl + "A4.mp3",
        Bb4: baseUrl + "Bb4.mp3",
        B4: baseUrl + "B4.mp3",

        C5: baseUrl + "C5.mp3",
        Db5: baseUrl + "Db5.mp3",
        D5: baseUrl + "D5.mp3",
        Eb5: baseUrl + "Eb5.mp3",
        E5: baseUrl + "E5.mp3",
        F5: baseUrl + "F5.mp3",
        Gb5: baseUrl + "Gb5.mp3",
        G5: baseUrl + "G5.mp3",
        Ab5: baseUrl + "Ab5.mp3",
        A5: baseUrl + "A5.mp3",
        Bb5: baseUrl + "Bb5.mp3",
        B5: baseUrl + "B5.mp3",

        C6: baseUrl + "C6.mp3",
        Db6: baseUrl + "Db6.mp3",
        D6: baseUrl + "D6.mp3",
        Eb6: baseUrl + "Eb6.mp3",
        E6: baseUrl + "E6.mp3",
        F6: baseUrl + "F6.mp3",
        Gb6: baseUrl + "Gb6.mp3",
        G6: baseUrl + "G6.mp3",
        Ab6: baseUrl + "Ab6.mp3",
        A6: baseUrl + "A6.mp3",
        Bb6: baseUrl + "Bb6.mp3",
        B6: baseUrl + "B6.mp3",

        C7: baseUrl + "C7.mp3",
        Db7: baseUrl + "Db7.mp3",
        D7: baseUrl + "D7.mp3",
        Eb7: baseUrl + "Eb7.mp3",
        E7: baseUrl + "E7.mp3",
        F7: baseUrl + "F7.mp3",
        Gb7: baseUrl + "Gb7.mp3",
        G7: baseUrl + "G7.mp3",
        Ab7: baseUrl + "Ab7.mp3",
        A7: baseUrl + "A7.mp3",
        Bb7: baseUrl + "Bb7.mp3",
        B7: baseUrl + "B7.mp3",
    };
};

export const Instruments: Array<Instrument> = InstrumentNames.map((name) => {
    return {
        name: name.replace(/^_*(.)|_+(.)/g, (s, c, d) =>
            c ? c.toUpperCase() : " " + d.toUpperCase()
        ),
        id: name,
        urls: GetInstrumentUrls(name),
        release: 1,
        attack: 0,
    };
});
